TOWNS = [
    {"id": "girona", "name": "Girona", "comarca": "Gironès", "km_gi": 0, "km_bcn": 100, "km_jq": 60},
    {"id": "salt", "name": "Salt", "comarca": "Gironès", "km_gi": 3, "km_bcn": 103, "km_jq": 60},
    {"id": "sarria_ter", "name": "Sarrià de Ter", "comarca": "Gironès", "km_gi": 4, "km_bcn": 104, "km_jq": 58},
    {"id": "bescano", "name": "Bescanó", "comarca": "Gironès", "km_gi": 8, "km_bcn": 108, "km_jq": 65},
    {"id": "celra", "name": "Celrà", "comarca": "Gironès", "km_gi": 6, "km_bcn": 106, "km_jq": 55},
    {"id": "fornells", "name": "Fornells de la Selva", "comarca": "Gironès", "km_gi": 7, "km_bcn": 95, "km_jq": 65},
    {"id": "riudellots", "name": "Riudellots de la Selva", "comarca": "Selva", "km_gi": 10, "km_bcn": 90, "km_jq": 70},
    {"id": "cassa", "name": "Cassà de la Selva", "comarca": "Gironès", "km_gi": 14, "km_bcn": 95, "km_jq": 75},
    {"id": "llagostera", "name": "Llagostera", "comarca": "Gironès", "km_gi": 17, "km_bcn": 90, "km_jq": 80},
    {"id": "banyoles", "name": "Banyoles", "comarca": "Pla de l'Estany", "km_gi": 18, "km_bcn": 118, "km_jq": 50},
    {"id": "vilafant", "name": "Vilafant", "comarca": "Alt Empordà", "km_gi": 42, "km_bcn": 142, "km_jq": 20},
    {"id": "figueres", "name": "Figueres", "comarca": "Alt Empordà", "km_gi": 40, "km_bcn": 140, "km_jq": 22},
    {"id": "llers", "name": "Llers", "comarca": "Alt Empordà", "km_gi": 45, "km_bcn": 145, "km_jq": 15},
    {"id": "pont_molins", "name": "Pont de Molins", "comarca": "Alt Empordà", "km_gi": 43, "km_bcn": 143, "km_jq": 18},
    {"id": "biure", "name": "Biure d'Empordà", "comarca": "Alt Empordà", "km_gi": 50, "km_bcn": 150, "km_jq": 12},
    {"id": "capmany", "name": "Capmany", "comarca": "Alt Empordà", "km_gi": 53, "km_bcn": 153, "km_jq": 10},
    {"id": "agullana", "name": "Agullana", "comarca": "Alt Empordà", "km_gi": 55, "km_bcn": 155, "km_jq": 8},
    {"id": "la_jonquera", "name": "La Jonquera (frontera)", "comarca": "Alt Empordà", "km_gi": 60, "km_bcn": 160, "km_jq": 0},
    {"id": "castello_empuries", "name": "Castelló d'Empúries", "comarca": "Alt Empordà", "km_gi": 50, "km_bcn": 150, "km_jq": 25},
    {"id": "roses", "name": "Roses", "comarca": "Alt Empordà", "km_gi": 60, "km_bcn": 160, "km_jq": 30},
    {"id": "empuriabrava", "name": "Empuriabrava", "comarca": "Alt Empordà", "km_gi": 55, "km_bcn": 155, "km_jq": 28},
    {"id": "l_escala", "name": "L'Escala", "comarca": "Alt Empordà", "km_gi": 45, "km_bcn": 145, "km_jq": 40},
    {"id": "peralada", "name": "Peralada", "comarca": "Alt Empordà", "km_gi": 50, "km_bcn": 150, "km_jq": 18},
    {"id": "llanca", "name": "Llançà", "comarca": "Alt Empordà", "km_gi": 65, "km_bcn": 165, "km_jq": 20},
    {"id": "portbou", "name": "Portbou", "comarca": "Alt Empordà", "km_gi": 70, "km_bcn": 170, "km_jq": 15},
    {"id": "olot", "name": "Olot", "comarca": "Garrotxa", "km_gi": 45, "km_bcn": 130, "km_jq": 80},
    {"id": "santa_coloma", "name": "Santa Coloma de Farners", "comarca": "Selva", "km_gi": 35, "km_bcn": 100, "km_jq": 85},
    {"id": "blanes", "name": "Blanes", "comarca": "Selva", "km_gi": 55, "km_bcn": 65, "km_jq": 110},
    {"id": "lloret", "name": "Lloret de Mar", "comarca": "Selva", "km_gi": 50, "km_bcn": 70, "km_jq": 105},
    {"id": "barcelona", "name": "Barcelona", "comarca": "Barcelonès", "km_gi": 100, "km_bcn": 0, "km_jq": 160},
    {"id": "badalona", "name": "Badalona", "comarca": "Barcelonès", "km_gi": 105, "km_bcn": 8, "km_jq": 165},
    {"id": "hospitalet", "name": "L'Hospitalet de Llobregat", "comarca": "Barcelonès", "km_gi": 102, "km_bcn": 5, "km_jq": 162},
    {"id": "cornella", "name": "Cornellà de Llobregat", "comarca": "Baix Llobregat", "km_gi": 108, "km_bcn": 12, "km_jq": 168},
    {"id": "el_prat", "name": "El Prat de Llobregat", "comarca": "Baix Llobregat", "km_gi": 110, "km_bcn": 14, "km_jq": 170},
    {"id": "sabadell", "name": "Sabadell", "comarca": "Vallès Occidental", "km_gi": 120, "km_bcn": 25, "km_jq": 180},
    {"id": "terrassa", "name": "Terrassa", "comarca": "Vallès Occidental", "km_gi": 125, "km_bcn": 30, "km_jq": 185},
    {"id": "granollers", "name": "Granollers", "comarca": "Vallès Oriental", "km_gi": 90, "km_bcn": 30, "km_jq": 145},
    {"id": "mataro", "name": "Mataró", "comarca": "Maresme", "km_gi": 80, "km_bcn": 30, "km_jq": 135},
]


def get_town(town_id: str):
    return next((t for t in TOWNS if t["id"] == town_id), None)
